### ISSUE TITLE
Cover Art is not updating from Navidrome

### ISSUE THREAD

**Issue by LIONSEATLIONS** [keifufu/WebNowPlaying-Rainmeter#13]
I'm using v2.0.7 and the cover art doesn't update when listening from Navidrome, is just uses the last updated one. It updates just fine from other sources (Yandex Music for example)

**Comment by LIONSEATLIONS** [comment]
FYI Navidrome didn't update since February

**Comment by keifufu** [comment]
I haven't had any problems with Navidrome, I've been using it for all my music since you recommended adding support for it :3

So (assuming you're using rainmeter), this is likely an issue with the skin, although if it works fine with other players I guess it wouldn't be.

**Comment by LIONSEATLIONS** [comment]
> I haven't had any problems with Navidrome, I've been using it for all my music since you recommended adding support for it :3
> 
> So (assuming you're using rainmeter), this is likely an issue with the skin, although if it works fine with other players I guess it wouldn't be.

Glad to hear that you're enjoying Navidrome :)

Just figured out that it's working with the demo server but not my own server for some reason. It's strange since i didn't update my server at all since February)

**Comment by keifufu** [comment]
I get the album cover using the [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) api. You can check if it's properly set by pasting `navigator.mediaSession.metadata` in your console.

**Comment by LIONSEATLIONS** [comment]
appreciate it, I'll try checking it

**Comment by LIONSEATLIONS** [comment]
it seems like MediaSession is working, it's the same comparing to the demo. All links working fine
![image](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/assets/127344351/0cae9667-b34a-4afb-9989-9b4d3dcfff05)

**Comment by keifufu** [comment]
Since you're using Firefox, make sure to give the extension full permissions as described [here](https://wnp.keifufu.dev/extension/getting-started).

**Comment by LIONSEATLIONS** [comment]
already checked and also tried Edge as well, not the case

**Comment by keifufu** [comment]
Weird. Are you sure it's only the cover not being reported? The title and artist could be pulled from [Native APIs](https://wnp.keifufu.dev/desktop-players).

**Comment by LIONSEATLIONS** [comment]
unchecked Use Natives APIs and reconnected the extension. Everything except the cover loads

**Comment by keifufu** [comment]
I've got no clue and sadly no time to debug this right now. You can try asking for help on the [rainmeter discord](https://discord.gg/rainmeter).

**Comment by LIONSEATLIONS** [comment]
I really appreciate your help, I'll try to debug something myself tomorrow, maybe it's something wrong on my server or my machine. I'll write back if i find something

**Comment by LIONSEATLIONS** [comment]
a little update on the situation

using logging in Rainmeter i noticed this error
![image](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/assets/127344351/66b60287-8f7d-470f-96f4-85658c74f68c)

Seems like the plugin can parse the link successfully but somehow cannot download the image (the link is working just fine)

[Here is an example link to the cover](https://mtuci.space/playbeck/rest/getCoverArt?u=kevin_sheets&t=255a43acac7f784c785a94029a751c23&s=5710e5&f=json&v=1.8.0&c=NavidromeUI&id=mf-43ba4e918ce6470fa1f1599372c94f53&_=2022-08-04T08%3A59%3A34.187333588Z&size=300)

I had the same issue on two different machines, Windows 11 and Windows 10 and tried clean Rainmeter installation.

I also tried using custom Rainmeter skin to download the image (using the WebParsing plugin) and i succeeded

**Comment by keifufu** [comment]
Please enable debug logs in rainmeter and copy the debug log here.

**Comment by LIONSEATLIONS** [comment]
ERRO (22:55:05.494) : WebNowPlaying.dll - Unexpected error downloading https://mtuci.space/playbeck/rest/getCoverArt?u=kevin_sheets&t=255a43acac7f784c785a94029a751c23&s=5710e5&f=json&v=1.8.0&c=NavidromeUI&id=mf-c6f72bc483ece2af7a1c7d666bcae2e8&_=2023-09-18T04%3A48%3A00.052Z&size=300

DBUG (22:55:05.496) : WebNowPlaying.dll - Error Trace: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
   at WebNowPlaying.Measure.DownloadImageThread(String CoverUrl)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

**Comment by keifufu** [comment]
Thanks, I'll look into this soon.

**Comment by keifufu** [comment]
Is this issue still occurring? If so, it might be related to you using HTTP/3.

**Comment by keifufu** [comment]
I do not plan to fix this. If rewritten using [keifufu/WebNowPlaying-Library](https://github.com/keifufu/WebNowPlaying-Library) then this issue would be resolved but I have no plans of doing so as of now.

Fixing this without a rewrite is also possible, feel free to create a PR.

**Comment by keifufu** [comment]
wip

**Comment by keifufu** [comment]
Fixed in a pre-release. I do not recommend using it until it is stable though.
